inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.2

Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentHeredoc:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'combustion.gemspec'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/*'

Style/MultilineTernaryOperator:
  Exclude:
    - 'spec/dummy/db/migrate/*.rb'
