inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml

AllCops:
  Exclude:
    - 'gemfiles/*'
    - 'vendor/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/HeredocIndentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'combustion.gemspec'
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Exclude:
    - 'spec/dummy/db/migrate/*.rb'
