language: ruby
env:
  matrix:
    - "DB_ADAPTER=sqlite3"
    - "DB_ADAPTER=postgresql"
    - "DB_ADAPTER=mysql2"
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec appraisal install
script: 'bundle exec appraisal rspec'
services:
  - mysql
  - postgresql
