language: ruby
env:
  matrix:
    - "DB_ADAPTER=sqlite3"
    - "DB_ADAPTER=postgresql"
    - "DB_ADAPTER=mysql2"
rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - ./bin/literals
  - bundle exec appraisal install
script: 'bundle exec appraisal rake'
services:
  - mysql
  - postgresql
