language: ruby
dist: xenial
env:
  matrix:
    - "DB_ADAPTER=sqlite3"
    - "DB_ADAPTER=postgresql"
    - "DB_ADAPTER=mysql2"
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
before_install:
  - gem install bundler --version "~> 1.17"
install:
  - bundle _1.17.3_ install --jobs=3 --retry=3
before_script:
  - bundle exec appraisal install
script: bundle exec appraisal rake
services:
  - mysql
  - postgresql
